spring.application.name=vehiculos
# Puerto del servidor Backend
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehiculos_db
spring.datasource.username=postgres
spring.datasource.password=2009medellin

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Forzar la zona horaria a Colombia para consistencia en las reservas
spring.jackson.time-zone=America/Bogota