spring.application.name=vehiculos
# Puerto del servidor Backend
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehiculos_db
spring.datasource.username=postgres
spring.datasource.password=2009medellin

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Forzar la zona horaria a Colombia para consistencia en las reservas
spring.jackson.time-zone=America/Bogota

# Configuración de Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_contraseña_de_aplicacion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true